var annotated_dup =
[
    [ "AdminException", "classAdminException.html", null ],
    [ "AdminService", "classAdminService.html", "classAdminService" ],
    [ "Attribution", "classAttribution.html", "classAttribution" ],
    [ "Contact", "classContact.html", "classContact" ],
    [ "EmptyResponseDataStream", "classEmptyResponseDataStream.html", null ],
    [ "HealthException", "classHealthException.html", null ],
    [ "HealthService", "classHealthService.html", "classHealthService" ],
    [ "InfoThread", "classInfoThread.html", "classInfoThread" ],
    [ "Layer", "classLayer.html", "classLayer" ],
    [ "MessageDataStream", "classMessageDataStream.html", "classMessageDataStream" ],
    [ "Metadata", "classMetadata.html", "classMetadata" ],
    [ "OgcApiException", "classOgcApiException.html", null ],
    [ "OgcApiService", "classOgcApiService.html", "classOgcApiService" ],
    [ "Process", "classProcess.html", "classProcess" ],
    [ "Request", "classRequest.html", "classRequest" ],
    [ "Rok4Server", "classRok4Server.html", "classRok4Server" ],
    [ "Router", "classRouter.html", null ],
    [ "ServerConfiguration", "classServerConfiguration.html", "classServerConfiguration" ],
    [ "Service", "classService.html", "classService" ],
    [ "ServicesConfiguration", "classServicesConfiguration.html", "classServicesConfiguration" ],
    [ "TileMatrixSetInfos", "structTileMatrixSetInfos.html", null ],
    [ "TmsException", "classTmsException.html", null ],
    [ "TmsService", "classTmsService.html", "classTmsService" ],
    [ "WmsException", "classWmsException.html", null ],
    [ "WmsService", "classWmsService.html", "classWmsService" ],
    [ "WmtsException", "classWmtsException.html", null ],
    [ "WmtsService", "classWmtsService.html", "classWmtsService" ]
];