message(STATUS "Building a debian package")

set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Géoportail <tout_rdev@ign.fr>")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "WMS/WMTS/TMS server")
set(CPACK_DEBIAN_PACKAGE_SECTION "science")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
else()
  set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "i386")
endif()

set( CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${ROK4SERVER_SOURCE_DIR}/cmake/debian/postinst;" )

set(CPACK_BINARY_DEB "ON")
set(CPACK_GENERATOR "DEB")

