name: Build and release

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -y install gettext libfcgi-dev libtinyxml-dev zlib1g-dev libcurl4-openssl-dev libproj-dev libssl-dev libturbojpeg0-dev \
            libjpeg-dev libc6-dev librados-dev libboost-log-dev libboost-filesystem-dev libboost-system-dev libopenjp2-7-dev \
            libproj-dev libsqlite3-dev build-essential cmake

      - name: Build debian package
        run: |
          mkdir build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_VERSION=${{ github.ref_name }} -DOBJECT_ENABLED=1 ..
          make -j2
          make package

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      - name: Add debian package to release
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/rok4-server-${{ github.ref_name }}-linux-amd64.deb
          asset_name: rok4-server-${{ github.ref_name }}-ubuntu20.04-amd64.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Add TGZ package to release
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/rok4-server-${{ github.ref_name }}-linux-amd64.tar.gz
          asset_name: rok4-server-${{ github.ref_name }}-ubuntu20.04-amd64.tar.gz
          asset_content_type: application/vnd.debian.binary-package
